org: brittanisavery
app: siba
service: siba-api

custom:
  vars: ${file(vars.json)}
  defaultStage: dev
  profiles:
    dev: default
    prod: sibaHelper
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${opt:stage, self:provider.stage}}
  environment:
    COMMIS_EMAIL: ${self:custom.vars.${self:provider.stage}_commis_email}
    SIBA_EMAIL: ${self:custom.vars.siba_email}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

plugins:
  - serverless-offline

functions:
  join:
    handler: handler.join
    events:
      - http:
          path: siba/join
          method: post
          cors: true
  parse:
    handler: handler.parse
    events:
      - http:
          method: get
          path: siba/parse
          cors: true
          request:
            parameters:
              querystrings:
                url: true
                page: true
