org: brittanisavery
app: siba
service: siba-api

custom:
  vars: ${file(vars.json)}
  defaultStage: DEV
  profiles:
    dev: ${self:custom.vars.DEV_PROFILE}
    prod: ${self:custom.vars.PROD_PROFILE}
  serverless-offline:
    port: 4000

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage, self:custom.defaultStage}
  environment:
    NODE_ENV: ${self:provider.stage}
    COMMIS_EMAIL: ${self:custom.vars.${self:provider.stage}_COMMIS_EMAIL}
    SIBA_EMAIL: ${self:custom.vars.SIBA_EMAIL}
    DOMAIN: ${self:custom.vars.DOMAIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"

plugins:
  - serverless-offline

functions:
  join:
    handler: handler.join
    events:
      - http:
          path: siba/join
          method: post
          cors: true
  parse:
    handler: handler.parse
    events:
      - http:
          method: get
          path: siba/parse
          cors: true
          request:
            parameters:
              querystrings:
                url: true
                page: true
