name: Deploy CMS on Heroku

on:
  push:
    branches:
      - master
    paths:
      - "cms/**"
      - ".github/workflows/deploy-cms.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_CMS_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
