name: Deploy CMS on Heroku

on:
  push:
    branches:
      - master
    paths:
      - "cms/**"
      - ".github/workflows/deploy-cms.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add CMS remote origin
        run: git remote add heroku-cms https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_CMS_APP_NAME }}.git
      - name: Deploy CMS to Heroku
        run: git push heroku-cms `git subtree split --prefix cms master`:refs/heads/master --force
