name: Build/Deploy

on:
  push:
    branches: [ master ]
    paths: siba/**
  pull_request:
    branches: [ master ]
    paths: siba/**

jobs:
  build-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
        
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://ftp.averyincorporated.com//public_html/siba
        ftp-username: admin@averyincorporated.com
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: siba/build
